title: "刘翔的个人主页"
description: "个人学术主页"
url: "https://6LiuXiang9.github.io"
baseurl: ""

author:
  name    : "刘翔"
  avatar  : "images/avatar.jpg"
  bio     : "来自湖南。"
  location: "Hunan, China"
  employer: "HNFNU"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your@email.com"   # ← 填写你的邮箱

locale       : "zh-CN"
repository   : "6LiuXiang9/6LiuXiang9.github.io"
remote_theme : "academicpages/academicpages.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gzip

exclude:
  - "*.sh"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false

include:
  - _pages
